# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06f771a5efdd2c09f95ca0253759b70c"
name = "checkout-upsell"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,write_orders,write_metaobjects,write_metaobject_definitions,read_customers"

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/edited"
  topics = [ "orders/edited" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
