api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "upsell-discount"
type = "function"
uid = "5eb83118-9d94-09e4-9b02-94835b97cd30016fb812"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
